services:
  dnscrypt-parser:
    build: .
    container_name: dnscrypt-parser-scheduler
    environment:
      - DISPLAY=:99
    env_file:
      - .env
    volumes:
      - ./output:/app/output:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    network_mode: host
    restart: unless-stopped
    user: "1000:1000"
    command: >
      sh -c "
        Xvfb :99 -screen 0 1920x1080x24 &
        python scheduler.py
      "

  dnscrypt-parser-once:
    build: .
    container_name: dnscrypt-parser-once
    environment:
      - DISPLAY=:99
    env_file:
      - .env
    volumes:
      - ./output:/app/output:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    network_mode: host
    profiles:
      - manual
    user: "1000:1000"
    command: >
      sh -c "
        Xvfb :99 -screen 0 1920x1080x24 &
        python parser.py
      "